# -*- coding: utf-8 -*-
"""0411240078_MOHAMED_METAWEE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aD8u4g1aQ9w9iBoPDYSnRv-77c3Gnxdi

# ***Importing Liberries***
"""

from google.colab import drive
drive.mount('/content/drive')

"""**NOTE!!**

1- some cells gave **errors** i left it on purpose to see the way i was thinking in and the reasons to do some of the non obvious steps so you when running the file pleas just skape those cells.

2- if the fitting model gaves error just drom the NaN values agian and it will work.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import statsmodels.api as sm
from math import e
from scipy.stats import gmean
from scipy.stats import hmean
import plotly.express as pltly
plt.style.use('ggplot')

"""# ***Importing the data sets***"""

energy_usage=pd.read_csv('C:/Users/Mohamed/Desktop/world_data/API.csv', skiprows=4)
gdp=pd.read_csv('C:/Users/Mohamed/Desktop/world_data/API_NY.csv', skiprows=4)
cal=pd.read_csv('C:/Users/Mohamed/Desktop/world_data/daily-per-capita-caloric-supply.csv')

energy_usage.head()

gdp.head()

cal.head()

cal.rename(columns={"Entity":"Country Name","Code":"Country Code"},inplace=True)

cal.head()



"""# ***Data Cleaning and Preparation***

1. Dropping unnecessary columns
"""

eng=energy_usage.drop(columns=['Indicator Code', 'Indicator Name','Unnamed: 69'])
gdp.drop(columns=['Indicator Code', 'Indicator Name','Unnamed: 69'],inplace=True)

"""Because I got the calories usage from another source, and I will merge all the data sets together, there might be a difference in the way the same country was named, but the country code is more reliable, but also I will check that."""

print(sorted(eng['Country Name'].unique()) == sorted(cal['Country Name'].unique()))

"""There are some differences in naming some countries across the two data sets."""

print(sorted(eng['Country Code'].unique()) == sorted(cal['Country Code'].unique()))

eng_codes = eng['Country Code'].dropna().unique()
cal_codes = cal['Country Code'].dropna().unique()
print(sorted(eng_codes) == sorted(cal_codes))

eng_codes

cal_codes

l=set(eng_codes).symmetric_difference(set(cal_codes))

L=list(l)
L

for i in L:
    cont_lin=eng[eng['Country Code']==i]
    cont_nm=cont_lin['Country Name']
    print(i+' Satnds for: '+cont_nm)

"""As we see, the majority of the excess data is in fact either economical blends or regions. That means that keeping them in the data will affect our calculations because they might be calculated twice, so anyways, removing them from the data is the solution.
I will drop it latter.


NOTE: The only country that I observed was Kosovo, and it in fact has no data, just NaN values.

**=> Transforming the shape of the data.**
"""

eng_use=pd.melt(eng,
            id_vars=['Country Name', 'Country Code'],
            var_name='Year',
            value_name='KGOPC')

gdp_pc=pd.melt(gdp,
            id_vars=['Country Name', 'Country Code'],
            var_name='Year',
            value_name='GDPPC')

eng_use.sort_values(by='KGOPC',ascending=False).dropna()

gdp_pc.sort_values(by='GDPPC', ascending=False).dropna()

"""**Merging Data**"""

data=pd.merge(eng_use, cal, on=['Country Name', 'Year']).merge(gdp_pc,on=['Country Name', 'Year'])

eng_use.info()

"""the data type of the "Year" columns is different in the two sets so i will change the data type of the "Year" column from object to int"""

eng_use['Year']=eng_use['Year'].astype(int)

gdp_pc['Year']=gdp_pc['Year'].astype(int)

eng_use.info()

# Trying the same code againe
data=pd.merge(eng_use, cal, on=['Country Code', 'Year']).merge(gdp_pc,on=['Country Code', 'Year'])

data=data.drop(columns=['Country Name_y','Country Name']).rename(columns={'Country Name_x': 'Country Name'})

data=data.rename(columns={'Daily calorie supply per person':"CalPCPD"})

data

"""# ******The Analysis******"""

data.replace([np.inf, -np.inf], np.nan, inplace=True)
data.dropna(inplace=True)

eng_plot = sns.histplot(data['KGOPC'], kde=True,color="skyblue")
mean_val = data['KGOPC'].mean()
median_val = data['KGOPC'].median()
counts, bins = np.histogram(data['KGOPC'], bins='auto')
mode_val = bins[np.argmax(counts)] + (bins[1] - bins[0])/2
plt.axvline(mean_val, color='indigo', linestyle='--', linewidth=2, label=f'Ortalama: {mean_val:.2f}')
plt.axvline(median_val, color='goldenrod', linestyle='-', linewidth=2, label=f'Medyan: {median_val:.2f}')
plt.axvline(mode_val, color='teal', linestyle='-.', linewidth=2, label=f'Mod (Est): {mode_val:.2f}')
plt.ylim(top=600)
plt.legend()
plt.title("Energy Use (KgOPC) (Enerji Kullanımı)\ndağılımı ile ortalama, medyan ve mod\n")

print(f'STD: {data['KGOPC'].std()}')
print(f'variance: {data['KGOPC'].var()}')
print(f'Coefficient of Variation: {data['KGOPC'].var()/data['KGOPC'].mean()}')
print(f'skew: {data['KGOPC'].skew()}')
print(f'kurt: {data['KGOPC'].kurt()}')

eng_plot = sns.histplot(data['GDPPC'], kde=True,color="skyblue")
mean_val = data['GDPPC'].mean()
median_val = data['GDPPC'].median()
counts, bins = np.histogram(data['GDPPC'], bins='auto')
mode_val = bins[np.argmax(counts)] + (bins[1] - bins[0])/2
plt.axvline(mean_val, color='indigo', linestyle='--', linewidth=2, label=f'Ortalama: {mean_val:.2f}')
plt.axvline(median_val, color='goldenrod', linestyle='-', linewidth=2, label=f'Medyan: {median_val:.2f}')
plt.axvline(mode_val, color='teal', linestyle='-.', linewidth=2, label=f'Mod (Est): {mode_val:.2f}')
plt.ylim(top=700)
plt.legend()
plt.title("GDP per Capita (Kişi Başına Düşen GSYİH)\ndağılımı ile ortalama, medyan ve mod\n")

print(f'STD: {data['GDPPC'].std()}')
print(f'variance: {data['GDPPC'].var()}')
print(f'Coefficient of Variation: {data['GDPPC'].var()/data['GDPPC'].mean()}')
print(f'skew: {data['GDPPC'].skew()}')
print(f'kurt: {data['GDPPC'].kurt()}')

eng_plot = sns.histplot(data['CalPCPD'], kde=True,color="skyblue")
mean_val = data['CalPCPD'].mean()
median_val = data['CalPCPD'].median()
counts, bins = np.histogram(data['CalPCPD'], bins='auto')
mode_val = bins[np.argmax(counts)] + (bins[1] - bins[0])/2
plt.axvline(mean_val, color='indigo', linestyle='--', linewidth=2, label=f'Ortalama: {mean_val:.2f}')
plt.axvline(median_val, color='goldenrod', linestyle='-', linewidth=2, label=f'Medyan: {median_val:.2f}')
plt.axvline(mode_val, color='teal', linestyle='-.', linewidth=2, label=f'Mod (Est): {mode_val:.2f}')
plt.ylim(top=350)
plt.legend()
plt.title("Daily Caloric Intake per Capita\n(Kişi başına düşen günlük ortalama kilokalori miktarını)\ndağılımı ile ortalama, medyan ve mod\n")

print(f'STD: {data['CalPCPD'].std()}')
print(f'variance: {data['CalPCPD'].var()}')
print(f'Coefficient of Variation: {data['CalPCPD'].var()/data['CalPCPD'].mean()}')
print(f'skew: {data['CalPCPD'].skew()}')
print(f'kurt: {data['CalPCPD'].kurt()}')

# getting a sence of the correlation between different Parameters
sns.heatmap(
    data.select_dtypes(include='number').corr(),
    annot=True,
    cmap='coolwarm',
    vmin=-1, vmax=1,
    center=0
)

data.plot.scatter(x='KGOPC',y='GDPPC')

"""I noticed the heteroscedasticity of the KGOPC with GDPPC and also with CalPCPD, so I did a log-log transformation for the KGOPC with GDPPC and semi-log for the CalPCPD with GDPPC, of course depending on the scatter plot of the variables before the transformation.

**Now I want to see the correlation between the logs of the data.**
"""

data['Log_KGOPC']=np.log10(data['KGOPC'])
data['Log_GDPPC']=np.log10(data['GDPPC'])
data['Log_CalPCPD']=np.log10(data['CalPCPD'])

# the correlation heatmap
# getting a sence of the correlation between different Parameters
sns.heatmap(
    data.select_dtypes(include='number').corr(),
    annot=True,
    cmap='coolwarm',
    vmin=-1, vmax=1,
    center=0
)
plt.savefig("heatmap.png", dpi=400 ,bbox_inches='tight')

import matplotlib.patches as patches

plt.figure(figsize=(10, 6))
sns.scatterplot(
    data,
    x='KGOPC',
    y='GDPPC',
    hue='Country Name',
    legend=False
)
plt.title("X ekseninde KGOPC ve\nY ekseninde GDPPC'nin saçılım grafiği\n")
plt.savefig("X ekseninde KGOPC ve ekseninde GDPPC'nin saçılım grafiği.png", dpi=400 ,bbox_inches='tight')

plt.figure(figsize=(10, 6))
ax = sns.scatterplot(
    data,
    x='KGOPC',
    y='GDPPC',
    hue='Country Name',
    legend=False
)
ellipse1 = patches.Ellipse(
    xy=(16500, 55000),
    width= 5000,
    height= 25000,
    linewidth=2,
    edgecolor='navy',
    facecolor='none'
)
ellipse2 = patches.Ellipse(
    xy=(7400, 104000),
    width= 6000,
    height= 27000,
    linewidth=2,
    edgecolor='black',
    facecolor='none'
)
ax.add_patch(ellipse1)
ax.add_patch(ellipse2)
plt.text(13500,100000, "Moderate Energy & High GDP\n(Luxembourg)", color='black', ha='center')
plt.text(16000, 73000, "High Energy & Moderate GDP\n(Qatar & Iceland)", color='navy', ha='center')
plt.title("X ekseninde KGOPC ve\nY ekseninde GDPPC'nin saçılım grafiği\n")
plt.show()
plt.savefig("clusters.png", dpi=400 ,bbox_inches='tight')

pltly.scatter(data,x='KGOPC', y='GDPPC', color='Country Name')

data.plot.scatter(x='KGOPC',y='GDPPC',logx=True,logy=True)

pltly.scatter(data,x='Log_KGOPC', y='Log_GDPPC', color='Country Name')

data.plot.scatter(x='CalPCPD',y='GDPPC')

sns.scatterplot(data,x='CalPCPD', y='GDPPC', hue='Country Name',legend=False)

pltly.scatter(data,x='CalPCPD', y='GDPPC', color='Country Name')

data.plot.scatter(x='CalPCPD',y='GDPPC',logy=True)

data.plot.scatter(x='CalPCPD',y='GDPPC',logx=True,logy=True)

data

data.replace([np.inf, -np.inf], np.nan, inplace=True)
data.dropna(inplace=True)
y=data['Log_GDPPC']
x=data['Log_KGOPC']
x=sm.add_constant(x)
model=sm.OLS(y,x).fit()

model.summary()

y=data['Log_GDPPC']
x=data['CalPCPD']
x=sm.add_constant(x)
model12=sm.OLS(y,x).fit()

model12.summary()

y=data['Log_GDPPC']
x=data[['Log_KGOPC','Log_CalPCPD']]
x=sm.add_constant(x)
model2=sm.OLS(y,x).fit()

model2.summary()

test=data[data['Year']==1996]

y=test['Log_GDPPC']
x=test[['Log_KGOPC','Log_CalPCPD']]
x=sm.add_constant(x)
model3=sm.OLS(y,x).fit()

model3.summary()

y=data['Log_GDPPC']
x=data[['Log_KGOPC','CalPCPD']]
x=sm.add_constant(x)
model4=sm.OLS(y,x).fit()

model4.summary()

y=data['Log_GDPPC']
x=data[['Log_KGOPC','Year','CalPCPD']]
x=sm.add_constant(x)
model5=sm.OLS(y,x).fit()

model5.summary()





"""**Now, I have noticed that there are some outliers in the data in the first scatter plot**

but first we have to define exterem, as we see ther are very few data points that has KGOPC > 13k
"""

data[data['KGOPC']>13000]['Country Name'].unique()

A=0.1677
slope=1.1408
xline=np.linspace(data['KGOPC'].min(),data['KGOPC'].max())
yline= (10**A)*(xline**slope)

"""Those are the countries, but also those countries are way under the fitting line of the data."""

plt.figure(figsize=(10, 6))
sns.scatterplot(data,x='KGOPC', y='GDPPC',hue='Country Name', legend=False)
sns.lineplot(x=xline,y=yline)

"""so to know the extreme energy unsing countries, i would take to be the top 5% countries i.e 2 sigma above the average, but first lets take a look at the ditribution of the KGOPC"""

sns.histplot(data, x='KGOPC')

"""the data is not normally distributed so to find the top 5% we can normalize the data and then find the top 5% or we can use the quantile function.
in fact i wiil even make it very strict and take the top 1%.
"""

data['KGOPC'].quantile(0.99)

"""the top 1% KGOPC countries have a KGOPC > 11160"""

data[data['KGOPC']>11160]['Country Name'].unique()

"""but this raised a question, in the KGOPC vs GDPPC scatter plot we can find some points that has way greater GDPPC for way lower KGOPC, so I will introduce a paramater to find the effeciency of the energy usage."""

data['Energy Efficiency']=data['GDPPC']/data['KGOPC']

sns.histplot(data,x='Energy Efficiency')

data['Energy Efficiency'].quantile(0.95)

data[data['Energy Efficiency']>13.2]['Country Name'].unique()

"""now we have countries like: Yemen, Rep., Lesotho
these countries have a highe energy efficency becauce of other resons like for example lets investigate the Yemen case
"""

data[(data['Energy Efficiency']>13.2)&(data['Country Name']=='Yemen, Rep.')]

plt.figure(figsize=(10, 6))
sns.lineplot(data[data['Country Name']=='Yemen, Rep.'], x='Year', y='GDPPC')
sns.lineplot(data[data['Country Name']=='Yemen, Rep.'], x='Year', y='KGOPC')

"""this is why i introduced a new determinant to determin the energy efficient countries and that is the country should have a GDPPC top 5%"""

data['GDPPC'].mean()

data['GDPPC'].quantile(0.95)

# efficent countries in the worlid
data[(data['Energy Efficiency']>13.2)&(data['GDPPC']>48401.8)]['Country Name'].unique()

data.describe()

gdp_pc[gdp_pc['Country Name']=='World']

df_gdp_world = gdp_pc[gdp_pc['Country Name'] == 'World']
df_eng_world = eng_use[eng_use['Country Name'] == 'World']


fig, ax1 = plt.subplots(figsize=(10, 6))

color1 = 'tab:red'
ax1.set_xlabel('Yıl (Year)')
ax1.set_ylabel('GDP per Capita (USD)', color=color1, weight='bold')
line1 = ax1.plot(df_gdp_world['Year'], df_gdp_world['GDPPC'], color=color1, label='GDP per Capita')
ax1.tick_params(axis='y', labelcolor=color1)


ax2 = ax1.twinx()

color2 = 'tab:blue'
ax2.set_ylabel('Energy Use (KGOPC)', color=color2, weight='bold')
line2 = ax2.plot(df_eng_world['Year'], df_eng_world['KGOPC'], color=color2, label='Energy Use')
ax2.tick_params(axis='y', labelcolor=color2)


lines = line1 + line2
labels = [l.get_label() for l in lines]
ax1.legend(lines, labels, loc='upper left')

# 5. Add Title
plt.title("Dünya Geneli: Kişi Başına GSYİH ve Enerji Kullanımının Karşılaştırması\n(1960 - 2024)")

plt.show()
fig.savefig("zaman seri.png", dpi=400 ,bbox_inches='tight')

plt.savefig("my_plot.png", dpi=400, bbox_inches='tight')

plt.gcf()

A=0.1677
slope=1.1408
xline=np.linspace(data['Log_KGOPC'].min(),data['Log_KGOPC'].max())
yline=A+(slope*xline)

plt.figure(figsize=(10, 6))
sns.scatterplot(data, x='Log_KGOPC',y='Log_GDPPC', hue='Country Name', legend=False)
plt.title("Log-Log dönüşümü\n(Log_KGOPC & Log_GDPPC)")
plt.savefig("Log-Log dönüşümü.png", dpi=400 ,bbox_inches='tight')

plt.figure(figsize=(10, 6))
sns.scatterplot(data, x='Log_KGOPC',y='Log_GDPPC', hue='Country Name', legend=False)
sns.lineplot(x=xline,y=yline)
plt.title("Log-Log dönüşümünün uyum doğrusu\n(Log_KGOPC & Log_GDPPC)")
plt.savefig("Log-Log dönüşümü uyum doğrusu.png", dpi=400 ,bbox_inches='tight')

plt.figure(figsize=(10, 6))
sns.scatterplot(data, x='CalPCPD',y='GDPPC', hue='Country Name', legend=False)
plt.title("X ekseni CalPCPD \n Y ekseniLog_GDPPC")
plt.savefig("X ekseni CalPCPD Y ekseniLog_GDPPC.png", dpi=400 ,bbox_inches='tight')

A=1.0886
slope=0.0009
xline=np.linspace(data['CalPCPD'].min(),data['CalPCPD'].max())
yline=A+(slope*xline)

plt.figure(figsize=(10, 6))
sns.scatterplot(data, x='CalPCPD',y='Log_GDPPC', hue='Country Name', legend=False)
sns.lineplot(x=xline,y=yline)
plt.title("Yarı-Log dönüşümünün uyum doğrusu\nCalPCPD & Log_GDPPC")
plt.savefig("yari-Log dönüşümü uyum doğrusu.png", dpi=400 ,bbox_inches='tight')











